### ISSUE TITLE
Use labelSelector to have the master filter pods

### ISSUE THREAD

**Issue by elyscape** [datawire/telepresence#130]
Currently, Telepresence creates a deployment (or uses an existing one) and then uses the following process to identify which pod to attach to:

1. [export the deployment][export-deploy]
1. [grab the metadata][metadata]
1. [export all pods][export-pods]
1. for each pod, [check to see if its labels match those of the deployment][check-labels] and abort if not

This could be simplified significantly by using [the `--selector`/`-l` flag in `kubectl`][kubectl-get]. If you want to get a list of all pods that have the label `labelOne` set to `first` and `labelTwo` set to `second`, you can run `kubectl get pods --selector labelOne=first,labelTwo=second`. This is also supported by [the Kubernetes API][kubeapi-list-pods].

Another benefit to doing this is that it would make it easier to support, as an example, [OpenShift Origin][origin], which uses `DeploymentConfig`s instead of `Deployment`s; instead of requiring that the remote image run in a `Deployment`, you could allow the user to specify a set of labels to query on and use a matching pod.

[export-deploy]: https://github.com/datawire/telepresence/blob/0.42/cli/telepresence#L315-L324
[metadata]: https://github.com/datawire/telepresence/blob/0.42/cli/telepresence#L334
[export-pods]: https://github.com/datawire/telepresence/blob/0.42/cli/telepresence#L336-L342
[check-labels]: https://github.com/datawire/telepresence/blob/0.42/cli/telepresence#L351-L354
[kubectl-get]: https://kubernetes.io/docs/user-guide/kubectl/v1.5/#get
[kubeapi-list-pods]: https://kubernetes.io/docs/api-reference/v1.5/#list-62
[origin]: https://github.com/openshift/origin

**Comment by itamarst** [comment]
Thanks for the suggestion, and the detailed explanation!

Is this an immediate issue, or just a potential improvement? E.g. are you trying to use Telepresence with Origin at the moment?

**Comment by elyscape** [comment]
Indeed I am, and I'm in the process of writing up some other issues related to that.

**Comment by itamarst** [comment]
Thank you, we really appreciate it. I'll start thinking about what a good UX for this would look like. Seems like there's really two issues:

1. Telepresence presumes a `Deployment`, when really there could just be a `Pod`.
2. The way pods are looked up for a Deployment is inefficient.

For the first, then, perhaps the solution is a new alternative to `--deployment` and `--new-deployment`:

```
$ telepresence --selector labelOne=first --run-shell
```

Basically a corresponding option to the `kubectl` one.

More broadly for OpenShift my guess is that some custom support specifically for OpenShift would probably make for a nicer UX. Haven't looked at in detail yet, but that was my impression from looking at the Deis Workflow PaaS.

**Comment by elyscape** [comment]
Another thing that should probably be considered is that, rather than using the default labels provided by `kubectl run`, it might be a good idea to manually specify something when creating the resource with the `--label`/`-l` flag. This would allow us to avoid issues if the default labels change. Additionally, it could simplify cleanup; if, say, we set a label `telepresence=$TIMESTAMP`, cleanup could be handled on all platforms with `kubectl/oc/whatever delete all -l telepresence=$TIMESTAMP`. As another bonus, using a label with a timestamp would fix #94.

**Comment by itamarst** [comment]
As far as OpenShift support goes, I feel like requiring the user to manually type in labels is bad UX. I'd rather do automatically the equivalent what the current code does, find matches for the named `DeploymentConfig`.

So UX would be either:

```
$ telepresence --openshift --new-deployment test --run-shell
```

Or possibly identical to current UX if OpenShift can be automatically detected.

**Comment by elyscape** [comment]
It should be possible to detect OpenShift by hitting the `/version/openshift` endpoint on the API server. OpenShift returns 200 and a JSON document, but Kubernetes should return a 404.

**Comment by itamarst** [comment]
I am going to follow some of @elyscape 's suggestions.

1. For `--deployment` we need to continue with the current scheme, of looking up Depolyment and extracting its spec.
2. For `--new-deployment`, however, we can add custom label of `telepresence: <uuid>` in both --run and in spec, and then use that to clean up by deleting everything with that label. Also, use --restart=Always rather than explicitly asking for Deployment.

This would fix #94, as @elyscape suggested, and limit usage of Deployment to just one place (the code we use to find a pod). So that would limit places where OpenShift would need to be special-cased.

**Comment by elyscape** [comment]
@itamarst Ultimately the stated reason behind this issue hasn't quite been fixed. Instead of using `-l`/`--selector` when querying for the pod to have the master perform filtering, we're still retrieving all the pods and filtering them manually.

**Comment by itamarst** [comment]
I don't see any way to get rid of that completely given the existence of `--deployment` though. I could require adding a label but inevitably people would forget to add the label.
