### ISSUE TITLE
Support running the remote image as non-root

### ISSUE THREAD

**Issue by elyscape** [datawire/telepresence#131]
Kubernetes is [working on support for Security Contexts][securitycontext]. These would, among other things, allow a cluster to be configured such that pods are prohibited from running as root. In fact, this is the default mode for [OpenShift Origin][origin]. Unfortunately, the Telepresence Docker image needs to be run as root:
```shellsession
scapeless:~ elyscape$ docker run -it --rm --user=1000050000 datawire/telepresence-k8s:0.42
Could not load host key: /etc/ssh/ssh_host_rsa_key
Could not load host key: /etc/ssh/ssh_host_dsa_key
Could not load host key: /etc/ssh/ssh_host_ecdsa_key
Could not load host key: /etc/ssh/ssh_host_ed25519_key
sshd: no hostkeys available -- exiting.
```
This can be handled with two changes:

1. Bind the SSH daemon to a non-privileged port (i.e. some port >= 1024).
1. Add group read permissions to the files in `/etc/ssh`. When using a custom UID, Kubernetes sets the default group to 0 with a supplemental group equal to the UID. Sample output from inside a pod:
```shellsession
sh-4.2$ id
uid=1000050000 gid=0(root) groups=0(root),1000050000
```

[securitycontext]: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/security_context.md
[origin]: https://github.com/openshift/origin

**Comment by elyscape** [comment]
After doing some experimentation, it looks like giving group read permissions to the host keys causes `sshd` to barf on startup. I'm doing some digging now on how this might be circumvented.

**Comment by elyscape** [comment]
Okay, so it looks like what happens is that `sshd` barfs on startup if the host keys are group- or world-accessible *and* you're running as the owner. The trick therefore is to make them group-readable and have a line that reads `USER 1000`, so that the image will never run as root.

**Comment by itamarst** [comment]
Did you actually succeed in running opensshd as a non-root user in a way that allows logins as that user? All my attempts have failed so far (ditto for dropbear as well as twisted conch, a Python SSH server).

**Comment by elyscape** [comment]
Looks like the user needs to exist, which is frustrating given that OpenShift Origin assigns a UID that isn't known ahead of time. I'll do some digging.

**Comment by elyscape** [comment]
Okay, so it looks like there absolutely needs to be an entry in `/etc/passwd` for sshd to accept a user, even if you fudge things with PAM to accept all login attempts. The good news is that [there is a tool called nss_wrapper][nss_wrapper] that lets you redirect applications' queries to a user-controlled `passwd` file, which would allow you to dynamically figure that out at runtime [by doing something like this][sample-usage]. The bad news is that [there is no nss_wrapper package on Alpine][alpine-nss_wrapper].

[nss_wrapper]: https://cwrap.org/nss_wrapper.html
[sample-usage]: https://github.com/sclorg/s2i-python-container/blob/baf8c10/3.5/contrib/etc/generate_container_user
[alpine-nss_wrapper]: https://bugs.alpinelinux.org/issues/6710

**Comment by elyscape** [comment]
I got it to work! Add `UsePrivilegeSeparation no` to `/etc/ssh/sshd_config` and you should be good to go; it will execute as whatever user you run `sshd` as.

**Comment by itamarst** [comment]
Hm, I did try with UsePrivilegeSeparation, but perhaps the issue I had was lack of `-N` when doing manual testing. Thanks for the cross-check!
