### ISSUE TITLE
Support OpenShift Origin

### ISSUE THREAD

**Issue by elyscape** [datawire/telepresence#132]
This tool seems very useful, but does not currently work with [OpenShift Origin][origin], which is based on Kubernetes. Some fairly minor changes are needed to get Telepresence working with Origin:

1. [x] Allow the remote pod to be run as non-root (#131)
1. [x] Improve logic for identifying the remote pod (related to #130)
1. [x] Allow configuration of the binary to run (e.g. call `oc` instead of `kubectl`)
1. [x] Either:
    1. create a pod directly or
    1. let the server choose which generator to use

For item 4.ii, the generator can be guided by the `--restart` flag to `kubectl/oc run`. When provided `--restart=Always`, [`kubectl` will create a `Deployment`][kubectl-generators] and [`oc` will create a ` DeploymentConfig`][oc-generators].

[origin]: https://github.com/openshift/origin
[kubectl-generators]: https://kubernetes.io/docs/user-guide/kubectl-conventions/#generators
[oc-generators]: https://github.com/openshift/origin/blob/v1.4.1/docs/man/man1/oc-run.1#L43-L45

**Comment by itamarst** [comment]
Thanks for the detailed gap analysis!

Additional thought: item 3 could be done manually, but might be nice if there was some autodetection. Like, "I'm in an OpenShift repo, switch to `oc`" or something.

Beyond working at all, there's also working naturally as part of the OpenShift workflow. Telepresence needs some work just for Kubernetes (see #9), and similar work would probably make OpenShift nicer. That is:

1. I am OpenShift user, I have some config for my service (or whatever OpenShift calls it). My service is running in OpenShift.
2. Oops, bug report, I want to run a local copy and proxy it into OpenShift. I therefore want to automatically, with no editing/typing, swap out a telepresence proxy for my existing service.
3. Done with that, want to swap back to the real image.

Something like that. That might be easier to think through given some real world usage, so this won't be part of an initial OpenShift support goal.

**Comment by itamarst** [comment]
Current thoughts on implementation plan:

1. Do #131.
2. Switch `--new-deployment` to rely on `--restart`.
3. Add a new `telepresence-openshift` command line tool that knows about `oc` and identifies things based on `DeploymentConfig` instead of `Deployment`.

**Comment by elyscape** [comment]
I'm not sure creating a new tool is really that necessary. By doing something like `kubectl/oc run telepresence --image=datawire/telepresence-k8s:0.42 --restart=Always --label telepresence=$TIMESTAMP`, and then identifying the pod with `kubectl/oc get pods --selector telepresence=$TIMESTAMP` and deleting resources with `kubectl/oc delete all --selector telepresence=$TIMESTAMP`, the only thing that should really need to be added is the ability to select which binary to use, and that could be autodetected. OpenShift exposes an endpoint `/version/openshift` on the API server, but I believe Kubernetes will return a 404.

**Comment by itamarst** [comment]
So, I think all the prerequisites are done... so plausibly all that needs doing (famous last words) is swap out `oc` for `kubectl` and `DeploymentConfig` for `Deployment`. I will attempt to do that next, testing against OpenShift Online version.

**Comment by itamarst** [comment]
Ah... it seems `oc` and `kubectl` share the same config and therefore the same context. So that means autodetection should be possible.

**Comment by itamarst** [comment]
Sketch of implementation:

1. Check if `oc` is in path. If not, switch straight to Kubernetes mode.
2. If yes, run `oc version` to verify it is OpenShift's `oc`. If it is.
3. Parse kube config, figure out server URL. Check if server has `/version/openshift` endpoint. If so, use `oc`. Otherwise use `kubectl`.

If in OpenShift mode look for DeploymentConfig instead of Deployment. That should be only difference (theoretically...)

**Comment by itamarst** [comment]
I haven't done the conditional stuff, and tests aren't passing, but a simple end-to-end experiment of "can I run manually against OpenShift" appeared to work, so looking promising.

**Comment by itamarst** [comment]
Sketch of implementation:

1. Check if `oc` is in path. If not, switch straight to Kubernetes mode.
2. If yes, run `oc version` to verify it is OpenShift's `oc`. If it is.
3. Parse kube config, figure out server URL. Check if server has `/version/openshift` endpoint. If so, use `oc`. Otherwise use `kubectl`.

If in OpenShift mode look for DeploymentConfig instead of Deployment. That should be only difference (theoretically...)
