### ISSUE TITLE
Error trying to run telepresence on osx (Python 3.4 is too old, need 3.5+)

### ISSUE THREAD

**Issue by ntrvic** [datawire/telepresence#136]
My environment is osx 10.11.1 and python 3.4. After following the brew installation process, I tried to run telepresence but am getting the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence", line 914, in <module>
    main()
  File "/usr/local/bin/telepresence", line 868, in main
    args = parse_args()
  File "/usr/local/bin/telepresence", line 125, in parse_args
    "Telepresence: local development proxied to a remote Kubernetes "
TypeError: __init__() got an unexpected keyword argument 'allow_abbrev'
```

**Comment by itamarst** [comment]
Hi,

Thanks for the bug report. Python 3.5 is required, but I neglected to indicate that in the Homebrew dependencies, my apologies. I suggest manually upgrading to python 3.5 or 3.6 with homebrew.

I'll also update the dependencies so that happens automatically in the future.

**Comment by itamarst** [comment]
Oh, and additional bug this found: telepresence's automatic "do you want to file a bug?" code is not triggered if an error occurs during parsing arguments. So need to fix that too.

**Comment by itamarst** [comment]
Fixed in master.

**Comment by ntrvic** [comment]
Thank you!

**Comment by itamarst** [comment]
(Unfortunately it doesn't seem like Homebrew gives me any way to force an upgrade to newer Python, so I just added a nicer error on startup.)
