### ISSUE TITLE
Switch Travis CI to use build stages

### ISSUE THREAD

**Issue by itamarst** [datawire/telepresence#153]
Right now Linux and OS X builds run in parallel. Since the OS X build depends on the Linux build, this only works because OS X builds are so slow and so always get scheduled after the Linux one.

We should instead be doing build stages, now that Travis supports them: OS X after Linux. Need to figure out how to this works re releasing packages.

**Comment by exarkun** [comment]
#397 moves OS X builds to CircleCI with a configuration ("workflows" in CircleCI parlance) that takes care to build Docker images before letting the OS X build begin (hopefully eventually to be extended to Linux builds as well).

After #397 is resolved I expect that this issue will effectively be resolved as well.
