### ISSUE TITLE
Does telepresence solve my problem?

### ISSUE THREAD

**Issue by NathHorrigan** [datawire/telepresence#171]
Sorry, This isn't an issue but didn't know where else to put it. I'm developing an application but my laptop can no longer handle development. Does telepresence allow me to develop locally but have my remote services run the code, reducing the workload on my machine? Thanks!!

**Comment by richarddli** [comment]
Yes, Telepresence would be able to handle your use case, assuming your remote services running in a remote Kubernetes cluster? This is certainly one of the use cases. If you have specific questions, hop on our Gitter chat here: https://gitter.im/datawire/telepresence.
