### ISSUE TITLE
When using --swap-deployment please auto expose ports that the deployment expects exposed

### ISSUE THREAD

**Issue by plombardi89** [datawire/telepresence#185]

**Comment by rhs** [comment]
I ran into this as well. In my case the deployment doesn't actually specify any ports. They are only specified in my Dockerfile, however I think it would be relatively straightforward, and quite convenient, to infer a port to expose based on the service associated with the deployment.

**Comment by itamarst** [comment]
If no --expose is specified and no ports are detected, print out warning. Also should always print exposed ports, for security reasons. Finally, need to support case where --expose overrides auto-expose (specifically, we want to listen on different local port.)

And maybe there should also be a `--no-auto-expose`? Maybe if someone asks for it.
