### ISSUE TITLE
0.5.2: method=container: In telepresence.log docker complains `flag provided but not defined: --network`

### ISSUE THREAD

**Issue by mumoshu** [datawire/telepresence#201]
Hi, thanks for developing the great tool 😄 

With telepresence v0.5.2 and minikube v0.19.1 on my MBP, running the command below hangs after printing `Starting proxy...`:

```
telepresence --verbose --method container --swap-deployment myapp --expose 10010 --docker-run -i -t alpine /bin/sh
Starting proxy...
```

Browsing `telepresence.log` revealed that there are bunch of messages like the below:

```
Running: (['docker', 'run', '--network=container:telepresence-1498529316-7614348-43328', '--rm', 'datawire/telepresence-local:0.52', 'wait'],)... flag provided but not defined: --network
See 'docker run --help'.
```

According to the message, perhaps my docker client/server is too old so that it doesn't have `--network` flag?
Also, from which docker version does `--network` flag exist?

**Comment by itamarst** [comment]
Hi,

Sorry it's not working for you, and thanks for reporting the bug. What version of Docker are you using?

The Mac I've been testing with uses Docker for Mac, currently it's at 17.03-ce (so the March release I assume.) Are you perhaps on the old Docker Toolbox?

If you're on latest Docker for Mac, could you attach `telepresence.log`? Perhaps that will have some hints.

**Comment by mumoshu** [comment]
Hi @itamarst, it is v1.11.1, which is the one bundled in even the latest version of minikube.

Perhaps I'd better share some context there? I tend to run various docker commands against the docker daemon running inside minikube, not against a dedicated docker daemon running outside of minikube, so that I don't need to `docker push` every temporary docker images produced while testing. This way just `docker build -t foo/bar` and then `kube run --image foo/bar` could run the container faster, without pushing/pulling the image to/from the remote docker registry.

**Comment by itamarst** [comment]
Makes sense, yes, I often do that.

It looks like there's an open PR (2 hours old!) to update minikube's docker, so with any luck Minikube 0.21 will have a new enough Docker - I believe 0.12 was when this option was added. In the meantime, you can change `--network=container:...` to `--net=container:` in your local copy of telepresence, and I'm guessing it will work.

**Comment by itamarst** [comment]
PR has been merged, so this will definitely be in Minikube 0.21.
