### ISSUE TITLE
Docker cannot be found on OSX

### ISSUE THREAD

**Issue by vincentvanderweele** [datawire/telepresence#221]
### What were you trying to do?

Run telepresence in container mode

### What did you expect to happen?

The container is build and proxied from the remote kubernetes cluster

### What happened instead?

It crashes because docker cannot be found

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '-m', 'container', '--swap-deployment', 'user-service', '--expose', '3000', '--docker-run', '--rm', '-it', '-v', '/Users/vwee/go/src/github.com/fujitsueos/user-service:/go/src/github.com/fujitsueos/user-service', 'fujitsueos/user-service', 'sh', '-c', 'go get -v github.com/pilu/fresh && fresh']`
Version: `0.57`
Python version: `3.6.1 (default, Apr 19 2017, 14:24:39) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]`
kubectl version: `Client Version: v1.7.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin FL737.local 15.6.0 Darwin Kernel Version 15.6.0: Tue Apr 11 16:00:51 PDT 2017; root:xnu-3248.60.11.5.3~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence", line 131, in call_f
    return f(*args, **kwargs)
  File "/usr/local/bin/telepresence", line 1897, in go
    runner, remote_info, args, env, subprocesses, socks_port, ssh
  File "/usr/local/bin/telepresence", line 1664, in run_local_command
    p = Popen(docker_command, env=env)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'docker'

```

Logs:

```
0
>> iptables -t nat -A sshuttle-12300 -j RETURN --dest 127.0.0.1/32 -p tcp
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 10.244.1.0/24 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 10.244.2.0/24 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 10.244.0.0/24 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 192.168.0.0/16 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 192.168.65.1/32 -p udp --dport 53 --to-ports 12300 -m ttl ! --ttl 42
c : DNS request from ('172.17.0.2', 58308) to None: 41 bytes
2017-07-12T12:05:51+0000 [stdout#info] Set DNS suffix we filter out to: [b'local']
2017-07-12T12:05:51+0000 [stdout#info] Result for b'hellotelepresence.local' is ['127.0.0.1']
[INFO  tini (1)] Main child exited normally (with status '100')
Running: (['docker', 'run', '--help'],)... ran!

```

**Comment by itamarst** [comment]
Hi,

If you upgrade to Telepresence v0.58 this should be fixed natively.

Can I ask what you're using Telepresence for?

**Comment by vincentvanderweele** [comment]
Thanks!

I mean to use it to run my local code in a remote kubernetes cluster. So far I've been using a script to zip my source code, scp it to the cluster host, unzip, build a container, and add it to the cluster. It gets even more complicated when I want to debug the code remotely. Telepresence should make that all a whole lot easier.

I only started using it now but the first tests are promising!

**Comment by itamarst** [comment]
Cool, let us know if you have any problems or features you'd like added. You might also be interested in http://forge.sh, another tool we're working on.
