### ISSUE TITLE
Swap deployment preserves original command for container

### ISSUE THREAD

**Issue by jwickens** [datawire/telepresence#226]
when using --swap-deployment the original command (and I assume args) spec for the container is preserved. This causes the telepresence container to never start when the original spec specifies a command that does not exist in the telepresence container.

**Comment by itamarst** [comment]
Sorry you encountered a bug, and many thanks for reporting it. I'll go fix it (and I guess audit the Pod spec to see if there's anything else I should be modifying when swapping.)

**Comment by itamarst** [comment]
Looks like the following container options should be reset in swapped-out version:

* `command`
* `terminationMessagePolicy` (set this to stderr probably?)
* `livenessProbe`
* `readinessProbe`
* `args`

**Comment by itamarst** [comment]
OK, v0.59 should be available in about 30 minutes with a fix - let me know if it solves your problem!

By the way, what is your use case for Telepresence?

**Comment by itamarst** [comment]
OK, v0.59 is finally out (had to re-run build).
