### ISSUE TITLE
systemd-resolved (in some configurations?) breaks telepresence

### ISSUE THREAD

**Issue by itamarst** [datawire/telepresence#242]
See https://github.com/datawire/telepresence/issues/135#issuecomment-317188828 and following comment.

Tte way sshuttle works is to capture DNS packets going to configured nameservers and in /etc/resolv.conf and forward them to remote DNS server (in our case k8s proxy). The log attached in comment linked above shows no DNS packets being sent for `hellotelepresence`.

When systemd-resolved NSS plugin was removed from /etc/nsswitch.conf, however, everything worked. This suggests systemd-resolved NSS plugin is breaking resolution.

A plausible theory: caching, since this was issue on OS X as well. After first `hellotelepresence` the lack of domain is cached by OS X's resolver, which I solve by flushing its cache each time. systemd-resolved also does caching, so might have similar issue.

If that is the problem, we need to flush cache. Or, an even better idea: instead of always looking up some domain, look up `hellotelepresence1`, `hellotelepresence2`, `hellotelepresence3`, etc., so caching isn't an issue and we don't need to do custom per-platform cache clearing.

**Comment by itamarst** [comment]
Some testing by @farcaller suggests maybe the issue is not caching, but rather that systemd-resolved decides not to send single segment DNS records to DNS servers.

**Comment by itamarst** [comment]
From https://www.freedesktop.org/software/systemd/man/systemd-resolved.html:

> Single-label names are routed to all local interfaces capable of IP multicasting, using the LLMNR protocol. Lookups for IPv4 addresses are only sent via LLMNR on IPv4, and lookups for IPv6 addresses are only sent via LLMNR on IPv6. Lookups for the locally configured host name and the "gateway" host name are never routed to LLMNR.

Search domains are per-link, it sounds like as well, so lacking a search domain from DHCP, it seems like LLMNR is used, which means sshuttle won't capture those packets since they're not sent to DNS servers at all.

**Comment by itamarst** [comment]
Seems like it's possible to convince `sshuttle` (currently by patching its code) to capture packets sent via LLMNR - basically you have `sshuttle` capture packets going to 224.0.0.252:5355. This isn't *quite* the same as DNS, but possibly close enough that it'll just work. Otherwise we can modify Twisted's DNS parser, possibly.

So next need to test whether in telepresence case we can capture packets this way.

**Comment by itamarst** [comment]
The proposed fix seems to work.

Remaining:

* [ ] Tests pass on Travis, in particular Mac.
* [ ] Maybe back out new flush caching logic, since it's not relevant?
* [ ] This about how automated tests could work, given Travis doesn't have new enough thing.
* [ ] File ticket about upstreaming new `llmnr` sshuttle branch in our fork, update fork README.

**Comment by farcaller** [comment]
^ Tested, works for me

**Comment by itamarst** [comment]
0.62 should be released in next 30 minutes.
