### ISSUE TITLE
Clean up old resources in testing cluster in CI runs

### ISSUE THREAD

**Issue by itamarst** [datawire/telepresence#244]
We can leak Deployments, Services, Namespaces ands Pods in our tests; any such leak can cause problems. E.g. leaking Services makes Telepresence blow up if environment variables size exceeds ARG_MAX ("argument list too long" error).

To prevent, .travis.yml should run script that deletes all of those that are older than 24 hours and start with "testing-" prefix.

1. Don't do this as part of normal test scripts, so it doesn't trash users' minikube.
2. Prefix is so we don't delete built-in Services like "kubernetes" by mistake.
3. Older than 24 hours is so we don't break concurrent test runs.

**Comment by ark3** [comment]
This problem will go away if we switch to Kubernaut.
