### ISSUE TITLE
Prettify email subscription announcement

### ISSUE THREAD

**Issue by richarddli** [datawire/telepresence#266]
We should update the email subscription to a prettier look. I'm thinking of something simple like the attached screenshot.
![screen shot 2017-08-08 at 10 01 21 am](https://user-images.githubusercontent.com/10065494/29075497-92eb37b0-7c20-11e7-8db5-ecd22c80c4f8.png)

**Comment by ark3** [comment]
Was this fixed in d5f44b3? Is this done? @richarddli @sipplified

**Comment by richarddli** [comment]
Yes.
