### ISSUE TITLE
Package for Fedora 26

### ISSUE THREAD

**Issue by plombardi89** [datawire/telepresence#269]
We currently only support up to Fedora 25. Unfortunately the change is a little more involved than just adding `26` to the respective package build and upload code as the `alanfranz/fwd-*` Docker images have been superseded by `alanfranz/fpm-within-docker`.

I've already made this change in Kubernaut. It just needs to be ported over to here.

**Comment by ark3** [comment]
@plombardi89 How do you suggest testing this stuff? This seems like an easy fix but I want to have a post-change plan for testing, as it'll need to land on master to see packaging happen.

**Comment by budhrg** [comment]
It would be awesome to have this binary. :+1:

**Comment by plombardi89** [comment]
Fedora 27 is now out as well: https://fedoramagazine.org/announcing-fedora-27/

**Comment by richarddli** [comment]
Fixed with 0.72

**Comment by plombardi89** [comment]
Docs need an update. Still refer to Telepresence 25.  I would use 25+ if we're supporting 25, 26 and 27.

**Comment by budhrg** [comment]
> Docs need an update. Still refer to Telepresence 25. I would use 25+ if we're supporting 25, 26 and 27.

+1 @plombardi89

**Comment by richarddli** [comment]
Docs now say 26+. Should it say 25+?

**Comment by budhrg** [comment]
Working like a charm in Fedora 26 :+1:  Thanks.

**Comment by ark3** [comment]
Telepresence has native packages for Ubuntu Xenial, Zesty, and Artful, and for Fedora 26 and 27. 

With the release of Fedora 27, [Fedora 25 is no longer supported by Red Hat](https://fedoramagazine.org/fedora-25-end-life/), so there are no more [alanfranz/fpm-within-docker images](https://github.com/alanfranz/fpm-within-docker#fpm-within-docker) for it. As such, we have dropped support as well.
