### ISSUE TITLE
Consider moving Telepresence into datawireio/stable OS packaging repository

### ISSUE THREAD

**Issue by plombardi89** [datawire/telepresence#270]
Currently Telepresence lives in in `datawireio/telepresence` when RPM's and Debs are uploaded which is technically fine but as we build additional Datawire tool packages for Linux if we follow that pattern we will end up with `datawireio/forge` and `datawireio/kubernaut` among others. This means people need to continually add and install new repository files for each project... which is unnecessary and slows down update processes as caches need to be pulled from all the different repositories.

We should consolidate everything under `datawireio/stable` and mirror to `datawireio/telepresence` for backward compatibility.

**Comment by ark3** [comment]
@plombardi89 I'd like to land this and #269 simultaneously. Shall we discuss on Tuesday?
