### ISSUE TITLE
Expose multiple ports (using multiple --expose flags doesn't work)

### ISSUE THREAD

**Issue by natb1** [datawire/telepresence#280]
Using multiple expose flags appears to only expose the last port defined. This is how I tested:

```
telepresence --expose 4040 --expose 5050 --expose 6060 --run-shell
Volumes are rooted at $TELEPRESENCE_ROOT. See http://www.telepresence.io/howto/volumes.html for details.

Forwarding remote port 4040 to local port 4040.
Forwarding remote port 6060 to local port 6060.
Forwarding remote port 5050 to local port 5050.

Guessing that Services IP range is 100.64.0.0/13. Services started after this point will be inaccessible if are outside this range; restart telepresence if you can't access a new Service.

shell1$ nc -l 6060
```
```
telepresence --run-shell
shell2$ nc $THE_OTHER_TELEPRESENCE_CONTAINER.default.svc.cluster.local 6060
it works!
```
I see the message in shell 1
```
shell1$ nc -l 4040
```
```
shell2$ nc $THE_OTHER_TELEPRESENCE_CONTAINER.default.svc.cluster.local 4040
this message will never show up in shell 1
```

**Comment by ark3** [comment]
I'm having trouble replicating this. Here's what I'm doing.

Shell 1:

```
><> telepresence --method inject-tcp --expose 4000 --expose 5000 --run-shell
Starting proxy with method 'inject-tcp', which has the following limitations: Go programs, static binaries, suid programs, and custom DNS implementations are not supported. For a full list of method limitations see http://www.telepresence.io/reference/methods.html.
Volumes are rooted at $TELEPRESENCE_ROOT. See http://www.telepresence.io/howto/volumes.html for details.

Forwarding remote port 4000 to local port 4000.
Forwarding remote port 5000 to local port 5000.

@admin@kubernetes|:telepresence $ nc -l 5000
```

Shell 2:

```
><> cli/telepresence --method inject-tcp --run-shell
Starting proxy with method 'inject-tcp', which has the following limitations: Go programs, static binaries, suid programs, and custom DNS implementations are not supported. For a full list of method limitations see http://www.telepresence.io/reference/methods.html.
Volumes are rooted at $TELEPRESENCE_ROOT. See http://www.telepresence.io/howto/volumes.html for details.

No traffic is being forwarded from the remote Deployment to your local machine. You can use the --expose option to 
specify which ports you want to forward.

@admin@kubernetes|:telepresence $ kubectl get pods
NAME                                                    READY     STATUS    RESTARTS   AGE
qotm-3546375384-2w8kd                                   1/1       Running   0          1m
qotm-3546375384-njwkt                                   1/1       Running   0          1m
qotm-3546375384-sg2gc                                   1/1       Running   0          1m
telepresence-1504121587-9437451-5365-939188572-2h8g5    1/1       Running   0          5m
telepresence-1504121887-6865666-6045-3228680875-n2lvz   1/1       Running   0          13s
@admin@kubernetes|:telepresence $ kubectl describe pod telepresence-1504121587-9437451-5365-939188572-2h8g5 | fgrep IP
IP:             192.168.12.130
@admin@kubernetes|:telepresence $ echo "Hello from port 5k" | nc 192.168.12.130 5000
```

At that point I can see the message on shell 1. Then I launch the same thing on port 4000 and try the same test. It works.

Shell 1:
```
[...]
Hello from port 5k
@admin@kubernetes|:telepresence $ nc -l 4000
```

Shell 2:
```
@admin@kubernetes|:telepresence $ echo "Hello from port 4k" | nc 192.168.12.130 4000
```

Shell 1:
```
[...]
Hello from port 4k
@admin@kubernetes|:telepresence $ 
```

So as far as I can see, both ports were exposed successfully. Perhaps more details about your environment may help to shed some light on this. Thoughts?

**Comment by natb1** [comment]
Ah, I found it. It's not an environmental issue. The above test works for me as well. Thanks for putting the working test together for me.

I needed a way to get the IP of my pod when using --docker-run (and I don't have kubectl in my container). Somewhere I got the idea that POD_NAME.NAMESPACE.svc.cluster.local would resolve to the IP of the pod. It does not, but for one reason or another it does resolve to the IP of the service that telepresence stands up. Unfortunately, that service is only created for the last port.

```
telepresence --expose 4040 --expose 5050 --run-shell
...
Forwarding remote port 4040 to local port 4040.
Forwarding remote port 5050 to local port 5050.
...
xxxx|bash-3.2$ kubectl get service -l telepresence
NAME                                   CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
telepresence-1504135426-336094-63215   100.70.69.158   <none>        5050/TCP   1m
```

I'll have to find another way of getting the IP of the pod I'm in when using --docer-run. Any pointers? (I guess I could just put kubectl in my image barring any better options).

**Comment by natb1** [comment]
This is resolved for me. Thanks for the help. Though, you may consider putting the pod ip in an environment variable. As it is, in order to get the IP I need to put kubectl in my dev image and mount my kube creds as a volume. Then `POD_IP=$(kubectl get pod $TELEPRESENCE_POD -o jsonpath={.status.podIP})`

I'll also include how I'm using this to proxy my local spark driver through to the cluster. I don't know the best place for this info, but took a bit of research so maybe I can save someone a headache if they happen to search the issues.
```
if [[ "$TELEPRESENCE_POD" ]]; then

  POD_IP=$(kubectl get pod $TELEPRESENCE_POD -o jsonpath={.status.podIP})
  TELEPRESENCE_ARGS=" \
    --conf spark.driver.host=$POD_IP \
    --conf spark.driver.bindAddress=0.0.0.0 \
    --conf spark.driver.port=5050 \
    --conf spark.blockManager.port=6060"
fi

$SPARK_HOME/bin/spark-submit \
  --master $SPARK_MASTER \
  $TELEPRESENCE_ARGS \
  $SPARK_HOME/examples/src/main/python/pi.py 10
```

**Comment by richarddli** [comment]
@natb1 Would you be willing to write a short blog post on your setup and how you use it? We can link to it from the Telepresence docs. We're finding people using Telepresence for all sorts of stuff, and yours is an interesting use case (and, as you said, there is a bit of research necessary to do it properly).

**Comment by natb1** [comment]
I can do that. Can I name drop my company vizual.ai?

**Comment by richarddli** [comment]
Yes, of course. We like it when people talk publicly about Telepresence ;-).

**Comment by kelseyevans** [comment]
@natb1 Thanks for writing this blog post! If you want to send me an email (kelsey@datawire.io) with your T shirt size and shipping address I'd be happy to send you a Telepresence t shirt :)

**Comment by SemanticBeeng** [comment]
> This is resolved for me. Thanks for the help. 

@natb1 is this support to work with latest `telepresence` 2? https://github.com/telepresenceio/telepresence/issues/1608#issuecomment-811420598

Trying to figure out if multiple ports can be exposed and cannot quite believe it cannot be.
