### ISSUE TITLE
Travis runs fail with OSError: [Errno 7] Argument list too long

### ISSUE THREAD

**Issue by ark3** [datawire/telepresence#282]
Problem is likely blowing out one single environment variable, possibly the `PATH`, as [described on StackOverflow](https://stackoverflow.com/a/33924766/8060653).

**Comment by ark3** [comment]
Investigating via commit 2cf80d4

**Comment by itamarst** [comment]
When this happened to me it was due to a service leak in the testing cluser: more services means more environment variables. If so, long term fix is #244.

**Comment by ark3** [comment]
Yup, that's it. I'm disappointed that my GitHub issue search didn't surface that issue. Thanks.

**Comment by ark3** [comment]
Closing this as we resolved it by cleaning up the testing cluster. I also reverted the above in 2ac45f0.
