### ISSUE TITLE
Error trying to create a new (proxied) deployment

### ISSUE THREAD

**Issue by rushilagr** [datawire/telepresence#343]
### What were you trying to do?

The regular flow of creating a new proxied deployment via telepresence. 
I created a cluster on GKE and started my deployments. 
Then tried -> telepresence --new-deployment rails --expose 3000

### What happened instead?

Basically - Error from server (AlreadyExists): services "rails" already exists

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--new-deployment', 'rails', '--expose', '3000']`
Version: `0.68`
Python version: `3.6.3 (default, Oct  4 2017, 06:09:15) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]`
kubectl version: `Client Version: v1.8.1`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Rushils-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence", line 257, in call_f
    return f(*args, **kwargs)
  File "/usr/local/bin/telepresence", line 2370, in go
    runner, args
  File "/usr/local/bin/telepresence", line 1500, in start_proxy
    args.deployment, run_id = create_new_deployment(runner, args)
  File "/usr/local/bin/telepresence", line 1247, in create_new_deployment
    runner.get_kubectl(args.context, args.namespace, command)
  File "/usr/local/bin/telepresence", line 422, in get_kubectl
    self.kubectl(context, namespace, args), stderr=stderr
  File "/usr/local/bin/telepresence", line 395, in get_output
    result = unicode(check_output(*args, **kwargs).strip(), "utf-8")
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['kubectl', '--context', 'gke_upheo-cc58a_asia-east1-a_cluster-1', '--namespace', 'default', 'run', '--restart=Always', '--limits=cpu=100m,memory=256Mi', '--requests=cpu=25m,memory=64Mi', 'rails', '--image=datawire/telepresence-k8s:0.68', '--labels=telepresence=b31a7f81-20c3-487b-a57a-43007284121d', '--port=3000', '--expose']' returned non-zero exit status 1.

```

Logs:

```
_upheo-cc58a_asia-east1-a_cluster-1', 'cluster-info'],)...
   2.9 TL | [1] captured.
   2.9 TL | [2] Capturing: (['ssh', '-V'],)...
   2.9 TL | [2] captured.
   2.9 TL | [3] Capturing: (['which', 'torsocks'],)...
   2.9 TL | [3] captured.
   2.9 TL | [4] Capturing: (['which', 'sshfs'],)...
   2.9 TL | [4] captured.
   2.9 TL | [5] Capturing: (['kubectl', '--context', 'gke_upheo-cc58a_asia-east1-a_cluster-1', '--namespace', 'default', 'delete', '--ignore-not-found', 'all', '--selector=telepresence=b31a7f81-20c3-487b-a57a-43007284121d'],)...
   4.6 TL | [5] captured.
   4.6 TL | [6] Capturing: (['kubectl', '--context', 'gke_upheo-cc58a_asia-east1-a_cluster-1', '--namespace', 'default', 'run', '--restart=Always', '--limits=cpu=100m,memory=256Mi', '--requests=cpu=25m,memory=64Mi', 'rails', '--image=datawire/telepresence-k8s:0.68', '--labels=telepresence=b31a7f81-20c3-487b-a57a-43007284121d', '--port=3000', '--expose'],)...
Error from server (AlreadyExists): services "rails" already exists

```

**Comment by rushilagr** [comment]
My bad. A load balancer already existed thats why it was having trouble creating the new deployment.

**Comment by ark3** [comment]
Thanks for the bug report! I'm glad you figured out the underlying issue. Could you tell us about your use case? That will help us direct our development efforts.

**Comment by rushilagr** [comment]
Yeah this is something you could integrate into the interface and flow.

When creating a new proxied container which has to be exposed publicly via
a port, a loadBalancer needs to be both - created and deleted - along with
container creation and deletion respectively.

This could perhaps be automated in someway.

I've been using Kubernetes for a few months now. Stumbled across
telepresence just a few days back and I'm really really happy with the
tool. Has mad life much simpler.

Thanks and good work !

**Comment by rushilagr** [comment]
Just to add my use cases for the tool -

It's mainly for speeding up development of new services / features. And
also for debugging.

It's only been a few days, might use it for more things later on.
