### ISSUE TITLE
telepresence crash, -m vpn-tcp, general dns issues

### ISSUE THREAD

**Issue by Rkiouak** [datawire/telepresence#346]
### What were you trying to do?

Launch telepresence into a local openshift env(minikube-like, 'brew install openshift-cli')

### What did you expect to happen?

a telepresence shell with network access to the local openshift project

### What happened instead?

Crash on startup.

Additionally, when telepresence has been succeeding to start up, I am experiencing failure for dns resolution within the pods. Also, when using -m vpn-tcp, my macs dns resolution fails-- I'm still able to receive incoming traffic, but none of my requests out succeed.

(please tell us - the traceback is automatically included, see below)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--run-shell']`
Version: `0.71`
Python version: `3.6.3 (default, Oct  4 2017, 06:09:15) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]`
kubectl version: `Client Version: v1.7.6`
oc version: `oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7`
OS: `Darwin Matts-MBP.hsd1.ma.comcast.net 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence", line 259, in call_f
    return f(*args, **kwargs)
  File "/usr/local/bin/telepresence", line 2399, in go
    runner, remote_info, args, env, subprocesses, socks_port, ssh
  File "/usr/local/bin/telepresence", line 2128, in run_local_command
    connect_sshuttle(runner, remote_info, args, subprocesses, env, ssh)
  File "/usr/local/bin/telepresence", line 1920, in connect_sshuttle
    get_hellotelepresence()
  File "/usr/local/bin/telepresence", line 1907, in get_hellotelepresence
    format(next(counter))
  File "/usr/local/bin/telepresence", line 397, in get_output
    result = unicode(check_output(*args, **kwargs).strip(), "utf-8")
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence7')"]' returned non-zero exit status 1.

```

Logs:

```
000 [stdout#info] /usr/lib/python3.6/site-packages/twisted/python/threadpool.py:250:inContext
  49.6 14 | 2017-11-09T23:23:55+0000 [stdout#info] /usr/lib/python3.6/site-packages/twisted/python/threadpool.py:266:<lambda>
  49.6 14 | 2017-11-09T23:23:55+0000 [stdout#info] /usr/lib/python3.6/site-packages/twisted/python/context.py:122:callWithContext
  49.6 14 | 2017-11-09T23:23:55+0000 [stdout#info] /usr/lib/python3.6/site-packages/twisted/python/context.py:85:callWithContext
  49.6 14 | 2017-11-09T23:23:55+0000 [stdout#info] ./forwarder.py:31:resolve
  49.6 14 | 2017-11-09T23:23:55+0000 [stdout#info] ]
  49.6 14 | 2017-11-09T23:23:55+0000 [stdout#info] A query: b'notifications.google.com'
  49.6 14 | 2017-11-09T23:23:55+0000 [stdout#info] A query: b'ogs.google.com'
  49.6 14 | 2017-11-09T23:23:55+0000 [stdout#info] A query: b'ssl.gstatic.com'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

```

**Comment by ark3** [comment]
You may be seeing a DNS loop. Telepresence's `vpn-tcp` mode sends all DNS to the cluster so that services are resolved correctly. If your cluster is local to your own machine, and Telepresence did not detect that correctly, then the DNS query will loop until Telepresence gives up (and crashes -- sorry about that). We are still working out many edge cases with `vpn-tcp`, which is somewhat more fragile on the Mac than on Linux. 

I suggest trying out container mode. With Docker, Telepresence can take full control over networking without causing trouble for your Mac.

**Comment by Rkiouak** [comment]
Appreciate the docker note & the fast response, using telepresence --docker-run does indeed resolve.
