### ISSUE TITLE
Mac OSX repeatedly pointing DNS to localhost after using telepresence

### ISSUE THREAD

**Issue by bpicolo** [datawire/telepresence#354]
So I've got a sort of...fun one. After using telepresence (and probably forcefully quitting it at somepoint of another), my Mac has started to repeatedly attempt to point DNS at 127.0.0.1 (after switching to various VPNd networks primarily?)

It's unclear, however, how to correct it. Trying to parse through source now, but was hoping something like this would be documented (that is, what exactly does telepresence set such that it can be manually fixed if necessary). Though it's possible the answer is "it didn't set any permanent config" and it's just OSX going nuts because it saw dns at 127.0.0.1 that one time

It's also possible I just need to flush the poor mdns responder but with SIP in place there are all sorts of hurdles for that -_-. Perhaps will give that a shot soon.

**Comment by ark3** [comment]
Yikes. That's not the sort of _fun_ we want Telepresence to deliver. 

Assuming you're using the default vpn-tcp mode, Telepresence uses [sshuttle](http://sshuttle.readthedocs.io/en/stable/requirements.html#macos-freebsd-openbsd-pfsense), which uses [pf/pfctl](https://gist.github.com/tracphil/4353170) on the Mac. Something like `sudo pfctl -s all` or maybe `sudo pfctl -sR` might be a starting point to figuring out why things are b0rked. The latter lists the tokens that sshuttle releases when it quits normally.

Take a look at this trace:

```shell
><> telepresence
Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You may need to add cloud hosts with --also-proxy. For a full list of method limitations see https://telepresence.io/reference/methods.html
Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.

No traffic is being forwarded from the remote Deployment to your local machine. You can use the --expose option to specify which ports you want to forward.

Guessing that Services IP range is 10.3.240.0/20. Services started after this point will be inaccessible if are outside this range; restart telepresence if you can't access a new Service.

@gke_datawireio|bash-3.2$ sudo pfctl -sR
No ALTQ support in kernel
ALTQ related functions disabled
TOKENS:
PID      Process Name                 TOKEN                    TIMESTAMP
31593    pfctl                        9044459238090142957      0 days 00:00:05
31589    pfctl                        9044459238090142189      0 days 00:00:05
@gke_datawireio|bash-3.2$ exit
exit
><> sudo pfctl -sR
No ALTQ support in kernel
ALTQ related functions disabled
No pf starter references held
><> fgrep pfctl telepresence.log
  15.0 35 | >> pfctl -s Interfaces -i lo -v
  15.0 35 | >> pfctl -s all
  15.0 35 | >> pfctl -a sshuttle6-12300 -f /dev/stdin
  15.0 35 | >> pfctl -E
  15.1 35 | >> pfctl -s Interfaces -i lo -v
  15.1 35 | >> pfctl -s all
  15.1 35 | >> pfctl -a sshuttle-12300 -f /dev/stdin
  15.1 35 | >> pfctl -E
  22.4 35 | >> pfctl -a sshuttle6-12300 -F all
  22.4 35 | >> pfctl -X 9044459238090142957
  22.4 35 | >> pfctl -a sshuttle-12300 -F all
  22.4 35 | >> pfctl -X 9044459238090142189
><>                                                                          0 (reorg|✚2…) ~/d/telepresence TMN 17:37:42
```

The output of the `fgrep` command shows all the `pfctl` commands run by sshuttle. The commands at the 22.4 second mark are the shutdown commands. You can see that sshuttle releases the token numbers listed earlier in the trace.

Please let me know how it goes. I'm also curious to know how you're using Telepresence. Perhaps we can improve it to the point that it works well and cleanly for you.

**Comment by bpicolo** [comment]
Hmm, don't see any tokens remaining from telepresence.

I'm being told that we actually do intentionally run a DNS server on 127.0.0.1 for opendns, so let me talk with security people and figure out if that dns server that should usually be running is now wedged for some reason.

**Comment by bpicolo** [comment]
@ark3  as for use case, I was trying to prototype an environment with k8s/istio that allowed me to run a big set of services for a developer environment but, depending on the developer, proxy the traffic for a particular service to the instance that dev is running. Didn't quiiiite work out, not sure what the issue was though. Probably missing an istio sidecar process in the telepresence container.

**Comment by richarddli** [comment]
Thanks! We are actually working on something like this with Telepresence and Ambassador (our Envoy-based API Gateway). Would you be interested in testing this out when it's ready?

**Comment by bpicolo** [comment]
@richarddli  I was wondering if that was the goal, actually. Would definitely be interested

**Comment by richarddli** [comment]
Have you seen https://www.datawire.io/faster/? We've started writing docs on how our different open source tools (Forge, Telepresence, Ambassador) help create an end-to-end development workflow. If you're open to it, I'd also be happy to chat live about your use cases and how we're evolving these different things. (Or, we'll be at KubeCon!)

**Comment by bpicolo** [comment]
@richarddli Yeah, it's pretty easy to do something clean when everything fits on one box (or is generally small enough for everybody to run the whole thing). It's harder when there are 100+ devs and the app depends on 100+ microservices, hah.

**Comment by bpicolo** [comment]
Going to close this, mostly because the computer in question is no longer around. May be useful historically-looking but there's no further progress I can make here : P
