### ISSUE TITLE
Generalize build-linux.sh and .travis.yaml into a single widely usable (cloud) testing tool

### ISSUE THREAD

**Issue by exarkun** [datawire/telepresence#374]
`build-linux.sh` is the de facto testing command during development.

`.travis.yaml` contains the testing steps used for testing during continuous integration. 

Rather than having two definitions of what it means to run the test suite, there should be one.  It should be usable by developers (who have access to a Kubernetes cluster; perhaps only the telepresence-testing GKE cluster to start) and by CI.

Its use should be documented to ease the path to becoming a telepresence developer.

**Comment by richarddli** [comment]
Originally everything was in `.travis.yaml`. I wanted to refactor things out of that file into shell scripts so it would be easier to do local builds. In particular, Mac OS X builds on Travis get really slow in the afternoon EST. I didn't finish this work, though.

**Comment by exarkun** [comment]
Is `build-linux.sh` the result of this refactoring?  Or is it somewhere else (and is it worth using as the basis for this work)?

**Comment by richarddli** [comment]
I did the refactoring and cleanup in `build-macosx.sh` for the most part, with various fixes to the other packaging machinery as I went along. @ark3 started expanding on that work with `build-linux.sh`. So I think these two are the right places to start.

**Comment by ark3** [comment]
Yes, what @richarddli said is correct.

Related, but separate, it would be nice to be able to release outside of Travis too.
