### ISSUE TITLE
Telepresence testing in Travis should use the Datawire cluster

### ISSUE THREAD

**Issue by ark3** [datawire/telepresence#381]
The goal is to avoid having a unique Telepresence testing cluster that gets no attention otherwise.

**Comment by ark3** [comment]
Can someone (@plombardi89 or @richarddli or @rhs or someone else) confirm that this is (still) a goal?

**Comment by richarddli** [comment]
I would like for us to at a minimum switch to a preemptible (or spot instance) test cluster to minimize cost. Whether it should be its own or part of a bigger cluster is an engineering decision.

**Comment by plombardi89** [comment]
Just get it to a spot (AWS) or pre-emptible (GKE) setup for now. I don't want to take on any additional engineering work switching clusters.

**Comment by ark3** [comment]
I have addressed the cost-savings goal: The testing cluster's single node is now (as of Friday afternoon) configured as preemptible. 

How shall we address the goal stated in the description?

**Comment by plombardi89** [comment]
I don't really have any good reason why Telepresence tests should be running on the **prod** cluster so I don't think that's a goal that anyone has actually come up with. Consider this done for now and move on is my suggestion.

**Comment by ark3** [comment]
Closing as recommended. Let's open a new issue if this question/goal comes up again.
