### ISSUE TITLE
Crash 30sec to 5min after swapping deployment

### ISSUE THREAD

**Issue by jacobsee** [datawire/telepresence#382]
I am testing Telepresence out, and have a persistent problem swapping out deployments on my GKE cluster. I am running the following command:

`telepresence --namespace staging --swap-deployment pentagon --method inject-tcp --run-shell --verbose`

(I'm using inject-tcp because I'd like to be able to swap more than one out at a time, but I'm not getting that far. Same error happens with vpn-tcp method also though - I tried.)

After somewhere (seems to be random) in the realm of 30 seconds to 5 minutes, Telepresence reports `Proxy to Kubernetes exited. This is typically due to a lost connection.` with a stack trace to a failed `umount`, but that appears to be common with other issues here. This _only_ seems to happen with a swapped deployment. If I'm not trying to swap and just connect to the cluster with `telepresence`, it seems stable.

I have uploaded the relevant looking piece of the telepresence.log file to a gist [here](https://gist.github.com/jacobsee/63d54b1c1a198f15d5aaceb8ff8d13dd).

I am using MacOS 10.13.2.

Any ideas would be much appreciated.

**Comment by jacobsee** [comment]
An very persistent automatic sync by weaveworks/flux (which was also running on the cluster) caused this. This had nothing to do with telepresence - apologies. If anyone else happens upon this, the solution was to add the annotation `flux.weave.works/ignore: "true"` to any deployment that I intended to swap with telepresence.

**Comment by richarddli** [comment]
Thanks for tracking this down! (And sorry for the delay in not responding).
