### ISSUE TITLE
(enhancement) expose a container port locally while telepresenc-ing

### ISSUE THREAD

**Issue by blak3mill3r** [datawire/telepresence#387]
It would be useful to have the option to specify port(s) to expose *locally* in combination with telepresence's `--docker-run` option (all other traffic being proxied as usual).

I believe this is currently unsupported (I tried using `--docker-run` in combination with the `--expose` or `-p` options for `docker run`):

```
docker: Error response from daemon: conflicting options: port publishing and the container type network mode.
```

The use case I have in mind is to connect a development tool to a process running in the local telepresenced container.

Specifically: I have a Clojure web service running in a container, if I use telepresence with `--docker-run` then I am unable to connect a local `nREPL` client to it. If I use `--method=vpn-tcp` and run the Clojure process directly on the host, then this is possible, but this is not ideal.

**Comment by ark3** [comment]
Telepresence release 0.75 includes the fix for this issue. Please take a look and let us know if you run into any trouble. Thanks!

**Comment by blak3mill3r** [comment]
Works like a charm. Thank you!
