### ISSUE TITLE
telepresence crashed when trying to run the qotm example from the docs

### ISSUE THREAD

**Issue by djablonski** [datawire/telepresence#395]
### What were you trying to do?

Trying to run the qotm example from the docs
`telepresence --docker-run -i -t alpine /bin/sh`

### What did you expect to happen?

A local docker container with alpine and a shell running.

### What happened instead?

The traceback appeared, and it didn't work... :(

### Automatically included information

Command line: `['/usr/bin/telepresence', '--docker-run', '-i', '-t', 'alpine', '/bin/sh']`
Version: `0.73`
Python version: `3.6.3 (default, Oct  9 2017, 12:07:10) 
[GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]`
kubectl version: `Client Version: v1.8.3`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux djablonski.intern.epages.de 4.14.11-300.fc27.x86_64 #1 SMP Wed Jan 3 13:52:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/usr/share/telepresence/libexec/lib64/python3.6/site-packages/telepresence/cli.py", line 73, in call_f
    return f(*args, **kwargs)
  File "/usr/share/telepresence/libexec/lib64/python3.6/site-packages/telepresence/main.py", line 489, in go
    ssh,
  File "/usr/share/telepresence/libexec/lib64/python3.6/site-packages/telepresence/container.py", line 118, in run_docker_command
    TELEPRESENCE_LOCAL_IMAGE, "wait"
  File "/usr/share/telepresence/libexec/lib64/python3.6/site-packages/telepresence/runner.py", line 84, in check_call
    raise CalledProcessError(retcode, args)
subprocess.CalledProcessError: Command '(['docker', 'run', '--network=container:telepresence-1515438859-5155954-6689', '--rm', 'datawire/telepresence-local:0.73', 'wait'],)' returned non-zero exit status 1.

```

Logs:

```
Starting firewall with Python version 3.6.1
  43.1 38 | firewall manager: ready method name nat.
  43.1 38 | IPv6 enabled: False
  43.1 38 | UDP enabled: False
  43.1 38 | DNS enabled: True
  43.1 38 | TCP redirector listening on ('127.0.0.1', 12300).
  43.1 38 | DNS listening on ('127.0.0.1', 12300).
  43.1 38 | Starting client with Python version 3.6.1
  43.1 38 | c : connecting to server...
  43.1 TL | [40] Running: (['docker', 'run', '--network=container:telepresence-1515438859-5155954-6689', '--rm', 'datawire/telepresence-local:0.73', 'wait'],)...
  44.1 40 | [INFO  tini (1)] Spawned child process 'python3' with pid '7'
  44.1 38 | ssh: connect to host 172.17.0.1 port 44239: Host is unreachable
  44.2 38 | c : fatal: failed to establish ssh session (2)
  44.3 38 | [INFO  tini (1)] Main child exited normally (with status '99')
  54.6 40 | Failed to connect to proxy in remote cluster.
  54.6 40 | [INFO  tini (1)] Main child exited normally (with status '1')
  55.3 TL | [40] exit 1.

```

**Comment by ark3** [comment]
Sorry about the crash! It looks like the Telepresence container is unable to reach the host machine via the expected IP address. I'll need to experiment a bit on a Linux machine to understand what might be going wrong here. Is there anything special about your machine's network or Docker?

**Comment by joshua-foster-tessella** [comment]
Experiencing the same issue. I have no special docker or networking set-up.

**Comment by ark3** [comment]
If you connect to a bogus port on the default IP from within a Docker container, do you get a "Connection refused" as I do? Or do you see a "Host is unreachable" as the trace above indicates?

```shell
$ docker run --rm -it alpine sh
/ # route | fgrep default
default         172.17.0.1      0.0.0.0         UG    0      0        0 eth0
/ # nc -vvv 172.17.0.1 12345
nc: 172.17.0.1 (172.17.0.1:12345): Connection refused
sent 0, rcvd 0
/ # 
```

**Comment by djablonski** [comment]
I found the reason for this issue in my case. It's the previously used company VPN connection, which in some circumstances semms to take a while to restore all network settings correctly.
If waiting for more than a minute after closing that VPN connection, telepresence works fine. If I try within ~30 seconds after closing, it sometimes works and sometimes not.
Therefore the issue is closed from my point of view.
