### ISSUE TITLE
Enable CircleCI builds

### ISSUE THREAD

**Issue by exarkun** [datawire/telepresence#397]
Travis builds, particularly on OS X, can take an unreasonable amount of time (particularly in the afternoon when builds queue up and it might be dozens of minutes before one even starts).

CircleCI also offers OS X support.  It seems worth investigating further, including gaining some real-world experience with that system, to determine whether it might provide a better experience than the current travis-based experience.

**Comment by exarkun** [comment]
https://circleci.com/docs/2.0/admin-faq/#is-it-possible-to-run-iosmacos-builds-on-circleci is possibly interesting.

**Comment by exarkun** [comment]
We may need to move or duplicate our Linux builds on CircleCI as well.  We need the Telepresence Docker images to be built and that's currently not done by the OS X build.  But another possibility could be to have the OS X build also build images.

**Comment by plombardi89** [comment]
Isn't moving Linux builds going to happen eventually no matter what? If Circle works great for OS X we should just move the whole thing over to it... having to maintain two CI systems just feels like a long term PITA.

**Comment by exarkun** [comment]
I haven't tried running Linux builds on CircleCI yet ... but hopefully, yea, that will work fine and we can just do all of Telepresence CI there and stop using Travis-CI.
