### ISSUE TITLE
Telepresence CI sometimes leaks pods

### ISSUE THREAD

**Issue by exarkun** [datawire/telepresence#402]
Telepresence CI runs a cluster cleanup tool (`ci/clean-cluster.py`) after each test run.  This deletes old services and deployments.  This _should_ result in old pods being cleaned up but in practice it doesn't accomplish this with complete reliability.  There is some failure mode where the deployment which owns one of the test pods gets cleaned up but a pod nevertheless remains.

**Comment by ark3** [comment]
Here is a (temporary?) workaround...

```
$ gd ci/clean-cluster.py 
diff --git a/ci/clean-cluster.py b/ci/clean-cluster.py
index 77c57f5..3d400fc 100755
--- a/ci/clean-cluster.py
+++ b/ci/clean-cluster.py
@@ -101,7 +101,7 @@ def main():
 
     names = [
         name
-        for kind in ("svc", "deploy")
+        for kind in ("svc", "deploy", "po")
         for name in get_resources(kind, args.prefix, args.min_age)
     ]
     if not names:
```

**Comment by ark3** [comment]
Workaround applied in 0.75, followed by cleaning up of namespaces.
