### ISSUE TITLE
Trivially simplify --swap-deployment cleanup

### ISSUE THREAD

**Issue by exarkun** [datawire/telepresence#420]
The cleanup codepath for `--swap-deployment` deletes the Telepresence deployment created earlier and then re-applies the saved original deployment.  These steps are done separately and incur the cost two kubectl-mediated remote operations.

There is a `kubectl replace` which should serve to perform both of these tasks in one operation.  This slightly simplifies the code, reduces the number of failure modes, and probably makes Telepresence shutdown very slightly faster (_possibly_ even perceptibly so, for a sufficiently attentive user...).

**Comment by ofpiyush** [comment]
With #407, I've replaced `swap-deployment`  with the sum of 3 separate behaviours.

1. `copy-deployment` flag
1. `forward-traffic` flag
1. Scale the original deployment to 0 replicas.

That brings multiple steps back in favour of a little safety.

**Comment by exarkun** [comment]
Thanks for the reference.  It looks like the #407 branch still does a delete followed by an apply for cleanup, though, so it seems like it would also benefit from this change.

**Comment by ofpiyush** [comment]
It might have if it were doing those operations on the same deployment. 

It copies the deployment into a different new one `my-deployment` -> `my-deployment-[run-id]` and applies scaling to `my-deployment`
