### ISSUE TITLE
How to speed up Telepresence Startup Time?

### ISSUE THREAD

**Issue by richarddli** [datawire/telepresence#491]
Telepresence currently takes around half a minute or more to start up. Some users have reported this is too slow for their use case and have told us they are not using Telepresence currently as part of their development workflow because of this issue.

The goal of this issue is to document the reasons Telepresence startup is slow and estimate for each documented reasons:

1. How likely it is that code path is exercised: 
  - Not Likely (only occurs when using an obscure feature)
  - Somewhat Likely (probably happens for a good number of users)
  - Very Likely (almost everyone is impacted)

2. How much effort is needed to fix the issue: 
  - Low Effort (minutes or hours)
  - Medium Effort (1 or 2 days)
  - High Effort (3+ days)

Each reason should be converted into a GitHub issue. Once reasons are documented we will come up with a plan for which Issues to tackle.

**Comment by plombardi89** [comment]
I have enhanced this Issue with more detail around what we want to do. My guess is we have some amount of "known" reasons for why Telepresence startup is slow, some of which are likely floating as issues in this repository already.

## Immediate Steps:

1. Find those issues if they exist.
2. Ensure if there are any issues floating in the minds of @exarkun or @ark3 that they are documented as described in the primary issue.

## Next Steps

Prioritize either in this cycle or for next cycle.
