### ISSUE TITLE
doubt-creating torsocks error

### ISSUE THREAD

**Issue by exarkun** [datawire/telepresence#50]
I tried using the uncontainerized process support in 0.14 and the first line of output when my app starts up now is:

```
[Mar 21 11:17:26] ERROR torsocks[19467]: Unable to resolve. Status reply: 4 (in socks5_recv_resolve_reply() at socks5.c:666)
```

I don't know if this is a critical error preventing my app from networking properly or if it's just a warning that something non-critical that failed that I can safely ignore.

**Comment by itamarst** [comment]
I suspect it's just noise, but I see what you mean about it being confusing. I'll see what I can do.

**Comment by itamarst** [comment]
I see similar error when I do `python3 -m http.server 8080`. Looking at strace I see this communication with the SOCKS proxy:

```
sendto(4, "\5\360\0\3\7hexagon\0*", 14, 0, NULL, 0) = 14
recvfrom(4, "\5\4\0\0", 4, 0, NULL, NULL) = 4
```

Basically it's trying to resolve "hexagon", which is my computer's hostname, and that's failing because, of course, the Kubernetes pod has never heard of it.
