### ISSUE TITLE
poor terminal interactions between tmux and --new-shell

### ISSUE THREAD

**Issue by exarkun** [datawire/telepresence#51]
When I use `--new-shell` in a tmux session, if I type a command that reaches the edge of the terminal, the illusion of a teletype is shattered by incorrect linewrapping behavior.

[out.ogv.zip](https://github.com/datawire/telepresence/files/858636/out.ogv.zip)

**Comment by itamarst** [comment]
Thanks for the very thorough bug report, I'll see what I can figure out.
