### ISSUE TITLE
crashed during first run

### ISSUE THREAD

**Issue by voobscout** [datawire/telepresence#539]
### What were you trying to do?

following example from [installation guide](https://www.telepresence.io/tutorials/docker):
```telepresence --docker-run -i -t alpine /bin/sh```
### What did you expect to happen?

to be able to acess a cluster service locally
### What happened instead?

just the trace, nothing else
### Automatically included information

Command line: `['/nix/store/90fk5v20gsrsccp1kh3wj6xpm4bxv89n-telepresence-0.77/bin/telepresence', '--docker-run', '-i', '-t', 'alpine', '/bin/sh']`
Version: `0.77`
Python version: `3.6.4 (default, Dec 19 2017, 05:36:13) 
[GCC 6.4.0]`
kubectl version: `Client Version: v1.9.1`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux ipc 4.15.7 #1-NixOS SMP Wed Feb 28 09:21:39 UTC 2018 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/nix/store/90fk5v20gsrsccp1kh3wj6xpm4bxv89n-telepresence-0.77/lib/python3.6/site-packages/telepresence/cli.py", line 73, in call_f
    return f(*args, **kwargs)
  File "/nix/store/90fk5v20gsrsccp1kh3wj6xpm4bxv89n-telepresence-0.77/lib/python3.6/site-packages/telepresence/main.py", line 497, in go
    ssh,
  File "/nix/store/90fk5v20gsrsccp1kh3wj6xpm4bxv89n-telepresence-0.77/lib/python3.6/site-packages/telepresence/container.py", line 134, in run_docker_command
    TELEPRESENCE_LOCAL_IMAGE, "wait"
  File "/nix/store/90fk5v20gsrsccp1kh3wj6xpm4bxv89n-telepresence-0.77/lib/python3.6/site-packages/telepresence/runner.py", line 153, in check_call
    raise CalledProcessError(retcode, args)
subprocess.CalledProcessError: Command '['docker', 'run', '--network=container:telepresence-1522222907-6368186-15129', '--rm', 'datawire/telepresence-local:0.77', 'wait']' returned non-zero exit status 1.

```

Logs:

```
1)] Spawned child process 'python3' with pid '7'
  61.9 54 |    0.0 TL | Telepresence launched at Wed Mar 28 07:42:23 2018
  61.9 54 |    0.0 TL |   ['/usr/bin/entrypoint.py', 'proxy', '{"port": 42431, "cidrs": ["10.96.0.0/12"], "expose_ports": []}']
  62.0 54 |    0.0 TL | BEGIN SPAN cleanup.py:68(wait_for_exit)
  62.0 54 |    0.0 TL | Everything launched. Waiting to exit...
  62.6 54 | Starting sshuttle proxy.
  63.3 54 | firewall manager: Starting firewall with Python version 3.6.1
  63.3 54 | firewall manager: ready method name nat.
  63.3 54 | IPv6 enabled: False
  63.3 54 | UDP enabled: False
  63.3 54 | DNS enabled: True
  63.3 54 | TCP redirector listening on ('127.0.0.1', 12300).
  63.3 54 | DNS listening on ('127.0.0.1', 12300).
  63.3 54 | Starting client with Python version 3.6.1
  63.3 54 | c : connecting to server...
  72.2 55 | Failed to connect to proxy in remote cluster.
  72.3 55 | [INFO  tini (1)] Main child exited normally (with status '1')
  72.4 TL | [55] exit 1.

```

**Comment by ark3** [comment]
Sorry Telepresence crashed on you. It looks like you're hitting a timeout in container networking setup, similar to #340. We'll up-prioritize that fix for an upcoming release.

**Comment by voobscout** [comment]
here's an "original" idea - make it a configurable parameter. A usecase would be a slow vpn to k8 cluster or some other latency, perhaps even due to local machine, it'd be easier to let the user decide on the timeout. just my 2ct.
