### ISSUE TITLE
In VPN mode instead of exporting environment variables write them into a .env file

### ISSUE THREAD

**Issue by ddehghan** [datawire/telepresence#608]
This way they can be loaded by the IDE for debugging. 

Currently the IDE used for debugger (like PyCharm) is running in is own context and is not aware of the environment variables set by telepresence in the shell. But if these were written into a file they can easily be loaded by python into the correct environment. 

my workaround is to create a shell script to get the env and write it into a file. 

sed -i 's|TELEPRESENCE_ROOT.*|TELEPRESENCE_ROOT='"$TELEPRESENCE_ROOT"'|' ./app/.env

**Comment by ark3** [comment]
https://plugins.jetbrains.com/plugin/7861-env-file

**Comment by plombardi89** [comment]
https://plugins.jetbrains.com/plugin/9525--env-files-support is the more popular one

**Comment by ark3** [comment]
If we give Telepresence the ability to output an env file, eventually we'll need to decide which variant we generate. Here are a few options:

1. [Docker compose](https://docs.docker.com/compose/env-file/). No special treatment for quotation marks. Might be same code for `docker run --env-file`, which does not support multi-line values.
2. [Node dotenv package](https://www.npmjs.com/package/dotenv#rules). Fancy treatment of quotation marks.
3. [VS Code Python plugin](https://github.com/Microsoft/vscode-python/issues/544#issuecomment-358133405). Explicitly has no support for multi-line values.

Generating JSON avoids these concerns, but might not be as broadly useful.
